### ISSUE TITLE
Sobre actualización

### ISSUE THREAD

**Issue by TiszRol** [Txus5012/WFRP4e-Castellano#1]
Hola,
Primero felicitarte por la traducción ha sido muy útil todo este tiempo y se agradece mucho el esfuerzo.
Ha habido una reciente actualización del sistema wfrp4 y comentan que hay gente a la que le ha dejado de ir bien la traducción. Yo no me he atrevido a actualizar, simplemente quería saber si tienes pensado actualizar y si podemos ayudar de alguna manera.

De nuevo agradecerte el trabajo que has hecho con la traducción.
Un saludo,

**Comment by TiszRol** [comment]
Parece que todo funciona correctamente! Por lo visto era una falsa alarma. Igualmente, reitero, si necesitas algo, aquí estamos.
Gracias de nuevo por el esfuerzo

**Comment by Txus5012** [comment]
Hola. Muchas gracias.

La traducción debe actualizarse, pero he estado ocupado.
(Y honestamente, no tenía constancia de que de verdad había gente usándolo XD )

**Comment by TiszRol** [comment]
En el discord de foundry Español, ha corrido como la pólvora. Yo lo uso en
las partidas que emito en rol nl y el resto de mis compañeros que juegan
también

**Comment by Txus5012** [comment]
Seguramente lo actualizaré cuando salga la siguiente actualización del sistema.
