### ISSUE TITLE
No hace la tirada de carrera en la creación de personaje

### ISSUE THREAD

**Issue by VestrumManticore** [Txus5012/WFRP4e-Castellano#8]
Al activar el comando /char, al pulsar el botón de carrera no hace nada. 
Por otra parte, darte las gracias por la traducción, estaba pensando en hacer algo similar. Tengo mucho contenido oficial de este juego, aunque mucho en inglés. Si puedo ayudarte a hacer las traducciones oficiales realizadas por Devir a los otros módulos, cuenta conmigo. Me encantaría tener todo el contenido en español.

**Comment by Txus5012** [comment]
Hola. De nada, y gracias.
Si tienes un módulo que altera esa tirada, no es compatible con la traducción. Otros jugadores han comentado que hacían la creación de personaje en inglés y luego lo traducían.
El problema aquí es que el único módulo que tengo es el básico y por eso la traducción se limita a ese.

**Comment by VestrumManticore** [comment]
Pues cuando quieras nos ponemos en contacto y vemos si puedo ayudarte con la traducción de otros módulos; que yo si tengo.

**Comment by Txus5012** [comment]
Gracias, pero el que debería tenerlo soy yo XD
Si tienes Discord, mejor hablamos por ahí.

**Comment by VestrumManticore** [comment]
Vestrum#0129 ese es mi discord. Agrégame y lo hablamos

**Comment by VestrumManticore** [comment]
Yo para el foundry tengo el de días duros y el set inicial.  Los cuales
también tengo en español en físico.  Si quieres y me explicas podemos hacer
algo
