### ISSUE TITLE
Traducción de las carreras

### ISSUE THREAD

**Issue by JorgeGLZS** [Txus5012/WFRP4e-Castellano#9]
La traducción está genial y salvo por una cosa me va perfecto, así que gracias por el gran trabajo.
Por algún motivo las carreras (sus descripciones) es como si no estuvieran. Relaciona los nombres traducidos con su respectiva carrera en inglés en el compendio, pero sale como desvinculada de la descripción. Y es raro porque no pasa con ninguna otra cosa (habilidades, heridas, críticos, enfermedades, etc). Te adjunto abajo un ejemplo.
Un saludo y gracias.
![Ejemplo](https://user-images.githubusercontent.com/114858306/193450191-562fcce3-f2de-4e06-b131-88ef560d376e.png)

**Comment by Txus5012** [comment]
Hola. Gracias.
La traducción aún no está actualizada a la última versión del módulo. Lo que ves se debe a un cambio en los compendios.
Estoy preparando una nueva actualización, pero estoy esperando a que también lo haga Babele para poder traducir los diarios, entre otras cosas.

**Comment by JorgeGLZS** [comment]
A vale, genial entonces. Gracias por el esfuerzo, sigue así. 
Un saludo.
